# subcommands
complete -f -c pod -n '__fish_use_subcommand' -xa cache -d "Manipulate the CocoaPods cache"
complete -f -c pod -n '__fish_use_subcommand' -xa deintegrate -d "Deintegrate CocoaPods from your project"
complete -f -c pod -n '__fish_use_subcommand' -xa env -d "Display pod environment"
complete -f -c pod -n '__fish_use_subcommand' -xa init -d "Generate a Podfile for the current directory"
complete -f -c pod -n '__fish_use_subcommand' -xa install -d "Install project dependencies according to versions from a Podfile.lock"
complete -f -c pod -n '__fish_use_subcommand' -xa ipc -d "Inter-process communication"
complete -f -c pod -n '__fish_use_subcommand' -xa lib -d "Develop pods"
complete -f -c pod -n '__fish_use_subcommand' -xa list -d "List pods"
complete -f -c pod -n '__fish_use_subcommand' -xa outdated -d "Show outdated project dependencies"
complete -f -c pod -n '__fish_use_subcommand' -xa plugins -d "Show available CocoaPods plugins"
complete -f -c pod -n '__fish_use_subcommand' -xa repo -d "Manage spec-repositories"
complete -f -c pod -n '__fish_use_subcommand' -xa search -d "Search for pods"
complete -f -c pod -n '__fish_use_subcommand' -xa setup -d "Setup the CocoaPods environment"
complete -f -c pod -n '__fish_use_subcommand' -xa spec -d "Manage pod specs"
complete -f -c pod -n '__fish_use_subcommand' -xa trunk -d "Interact with the CocoaPods API (e.g. publishing new specs)"
complete -f -c pod -n '__fish_use_subcommand' -xa try -d "Try a Pod!"
complete -f -c pod -n '__fish_use_subcommand' -xa update -d "Update outdated project dependencies and create new Podfile.lock"

# options
complete -c pod -l allow-root -d "Allows CocoaPods to run as root"
complete -c pod -l silent -d "Show nothing"
complete -c pod -l version -d "Show the version of the tool"
complete -c pod -l verbose -d "Show more debugging information"
complete -c pod -l no-ansi -d "Show output without ANSI codes"
complete -c pod -l help -d "Show help banner of specified command"
