### options
complete -c pry -s e -d "A line of code to execute in context before the session starts"
complete -c pry -l exec -d "A line of code to execute in context before the session starts"
complete -c pry -l no-pager -d "Disable pager for long output"
complete -c pry -l no-history -d "Disable history loading"
complete -c pry -l no-color -d "Disable syntax highlighting for session"
complete -c pry -s f -d "Suppress loading of pryrc"
complete -c pry -s s -d "Only load specified plugin (and no others)."
complete -c pry -l select-plugin -d "Only load specified plugin (and no others)."
complete -c pry -s d "Disable a specific plugin."
complete -c pry -l disable-plugin -d "Disable a specific plugin."
complete -c pry -l no-plugins -d "Suppress loading of plugins."
complete -c pry -l plugins -d "List installed plugins."
complete -c pry -l simple-prompt -d "Enable simple prompt mode"
complete -c pry -l noprompt -d "No prompt mode"
complete -c pry -s r -d "`require` a Ruby script at startup"
complete -c pry -l require -d "`require` a Ruby script at startup"
complete -c pry -s I -d "Add a path to the $LOAD_PATH"
complete -c pry -l gem -d "Shorthand for -I./lib -rgemname"
complete -c pry -s v -d "Display the Pry version"
complete -c pry -l version -d "Display the Pry version"
complete -c pry -s c -d "Start the session in the specified context. Equivalent to `context.pry` in a session."
complete -c pry -l context -d "Start the session in the specified context. Equivalent to `context.pry` in a session."
complete -c pry -s h -d "Display this help message."
complete -c pry -l help -d "Display this help message."
