# subcommands
complete -f -c skylark -n '__fish_use_subcommand' -xa gusto -d "fetch gusto coupon"
complete -f -c skylark -n '__fish_use_subcommand' -xa jonathan -d "fetch jonathan coupon"
complete -f -c skylark -n '__fish_use_subcommand' -xa bamiyan -d "fetch bamiyan coupon"
complete -f -c skylark -n '__fish_use_subcommand' -xa yumean -d "fetch yumean coupon"
complete -f -c skylark -n '__fish_use_subcommand' -xa steak_gusto -d "fetch steak_gusto coupon"
complete -f -c skylark -n '__fish_use_subcommand' -xa steak_gusto -d "fetch grazie_gardens coupon"
complete -f -c skylark -n '__fish_use_subcommand' -xa aiya -d "fetch aiya coupon"
complete -f -c skylark -n '__fish_use_subcommand' -xa karayoshi -d "fetch karayoshi coupon"
complete -f -c skylark -n '__fish_use_subcommand' -xa tonkara_tei -d "fetch tonkara_tei coupon"
