complete -c terminal-notifier -o help -d "Display this help banner."
complete -c terminal-notifier -o version -d "Display terminal-notifier version."
complete -c terminal-notifier -o message -d "The notification message."
complete -c terminal-notifier -o remove -d "Removes a notification with the specified ‘group’ ID."
complete -c terminal-notifier -o list -d "If the specified ‘group’ ID exists show when it was delivered, or use ‘ALL’ as ID to see all notifications. The output is a tab-separated list."
complete -c terminal-notifier -o title -d "The notification title. Defaults to ‘Terminal’."
complete -c terminal-notifier -o subtitle -d "The notification subtitle."
complete -c terminal-notifier -o sound -d "The name of a sound to play when the notification appears. The names are listed in Sound Preferences. Use 'default' for the default notification sound."
complete -c terminal-notifier -o group -d "A string which identifies the group the notifications belong to. Old notifications with the same ID will be removed."
complete -c terminal-notifier -o activate -d "The bundle identifier of the application to activate when the user clicks the notification."
complete -c terminal-notifier -o sender -d "The bundle identifier of the application that should be shown as the sender, including its icon."
complete -c terminal-notifier -o appIcon -d "The URL of a image to display instead of the application icon (Mavericks+ only)"
complete -c terminal-notifier -o contentImage -d "The URL of a image to display attached to the notification (Mavericks+ only)"
complete -c terminal-notifier -o open -d "The URL of a resource to open when the user clicks the notification."
complete -c terminal-notifier -o execute -d "A shell command to perform when the user clicks the notification."
complete -c terminal-notifier -o ignoreDnD -d "Send notification even if Do Not Disturb is enabled."
