#####################
#     directory     #
#####################

TOP_DIR := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))
BIN_DIR = $(TOP_DIR)/bin
CONFIG_DIR = $(TOP_DIR)/config
MODULE_DIR = $(TOP_DIR)/modules
SOURCE_DIR = $(TOP_DIR)/src
TMP_DIR = $(TOP_DIR)/tmp

####################
#      targets     #
####################

# all
ALL_TARGETS +=
ALL_CLEAN_TARGETS +=
ALL_UPDATE_TARGETS +=

# core
CORE_TARGETS +=
ALL_TARGETS += CORE_TARGETS
CORE_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += CORE_CLEAN_TARGETS

# bash
BASH_TARGETS +=
ALL_TARGETS += BASH_TARGETS
BASH_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += BASH_CLEAN_TARGETS

# fish
FISH_TARGETS +=
ALL_TARGETS += FISH_TARGETS
FISH_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += FISH_CLEAN_TARGETS
FISH_UPDATE_TARGETS +=
ALL_UPDATE_TARGETS += FISH_UPDATE_TARGETS

# nano
NANO_TARGETS +=
ALL_TARGETS += NANO_TARGETS
NANO_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += NANO_CLEAN_TARGETS

# textlint
TEXTLINT_TARGETS +=
ALL_TARGETS += TEXTLINT_TARGETS
TEXTLINT_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += TEXTLINT_CLEAN_TARGETS

# tmux
TMUX_TARGETS +=
ALL_TARGETS += TMUX_TARGETS
TMUX_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += TMUX_CLEAN_TARGETS

# nvim
NVIM_TARGETS +=
ALL_TARGETS += NVIM_TARGETS
NVIM_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += NVIM_CLEAN_TARGETS

# lem
LEM_TARGETS +=
ALL_TARGETS += LEM_TARGETS
LEM_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += LEM_CLEAN_TARGETS
LEM_UPDATE_TARGETS +=
ALL_UPDATE_TARGETS += LEM_UPDATE_TARGETS

# irb
IRB_TARGETS +=
ALL_TARGETS += IRB_TARGETS
IRB_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += IRB_CLEAN_TARGETS
IRB_UPDATE_TARGETS +=
ALL_UPDATE_TARGETS += LEM_UPDATE_TARGETS

# spacemacs
SPACEMACS_TARGETS +=
ALL_TARGETS += SPACEMACS_TARGETS
SPACEMACS_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += SPACEMACS_CLEAN_TARGETS

# doomemacs
DOOMEMACS_TARGETS +=
ALL_TARGETS += DOOMEMACS_TARGETS
DOOMEMACS_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += DOOMEMACS_CLEAN_TARGETS

# skk
SKK_TARGETS +=
ALL_TARGETS += SKK_TARGETS
SKK_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += SKK_CLEAN_TARGETS

# peco
PECO_TARGETS +=
ALL_TARGETS += PECO_TARGETS
PECO_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += PECO_CLEAN_TARGETS

# alacritty
ALACRITTY_TARGETS +=
ALL_TARGETS += ALACRITTY_TARGETS
ALACRITTY_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += ALACRITTY_CLEAN_TARGETS

# phpactor
PHPACTOR_TARGETS +=
ALL_TARGETS += PHPACTOR_TARGETS
PHPACTOR_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += PHPACTOR_CLEAN_TARGETS

# nyxt
NYXT_TARGETS +=
ALL_TARGETS += NYXT_TARGETS
NYXT_CLEAN_TARGETS +=
ALL_CLEAN_TARGETS += NYXT_CLEAN_TARGETS

# npm
NPM_UPDATE_TARGET +=
ALL_UPDATE_TARGETS += NPM_UPDATE_TARGET

####################
#      include     #
####################

-include $(SOURCE_DIR)/make/*.mk
-include $(MODULE_DIR)/*/Makefile

####################
#     commands     #
####################

# install
.PHONY: core
core: $(CORE_TARGETS)

.PHONY: all
all: $(ALL_TARGETS)

# clean
.PHONY: core-clean
core-clean: $(CORE_CLEAN_TARGETS)

.PHONY: clean
clean: $(ALL_CLEAN_TARGETS)

# update
.PHONY: update
update: $(ALL_UPDATE_TARGETS)
