[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'luochen1990/rainbow'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'pelodelfuego/vim-swoop'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'pechorin/any-jump.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'

[[plugins]]
repo = 'Shougo/deol.nvim'
