BIN_DIR=$TOP_DIR/bin
CONFIG_DIR=$TOP_DIR/config
SRC_DIR=$TOP_DIR/src

CONFIG_HOMEBREW_DIR=$CONFIG_DIR/homebrew
CONFIG_APT_DIR=$CONFIG_DIR/apt
CONFIG_PKG_DIR=$CONFIG_DIR/pkg

SRC_SHELL_DIR=$SRC_DIR/shell
