# FISH_DIR = ~/.config/fish
# FISH_COMPLETION_DIR = ~/.config/fish/completions
# SELF_FISH_DIR = $(MODULE_DIR)/fish

# FISH_LOCAL_FILE = $(SELF_FISH_DIR)/local.fish
# FISH_LOCAL_FILE_SAMPLE = $(SELF_FISH_DIR)/local.fish.sample
# FISH_FUNCTIONS_FILE = $(SELF_FISH_DIR)/functions.fish
# FISH_FUNCTIONS_FILE_SAMPLE = $(SELF_FISH_DIR)/functions.fish.sample

# FISH_GHQ_COMPLETION_FILE=https://raw.githubusercontent.com/decors/fish-ghq/master/completions/ghq.fish
# FISH_DOCKER_COMPLETION_FILE=https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/fish/docker.fish
# FISH_DOCKER_COMPOSE_COMPLETION_FILE=https://raw.githubusercontent.com/docker/compose/master/contrib/completion/fish/docker-compose.fish

# FISH_CLEAN_TARGETS += fish-shell-clean
# FISH_TARGETS += fish-shell-install

# .PHONY: fish-shell-clean
# fish-shell-clean:
# 	rm -rf $(FISH_DIR)

# .PHONY: fish-shell-install
# fish-shell-install: $(FISH_LOCAL_FILE) $(FISH_FUNCTIONS_FILE) $(FISH_DIR) $(FISH_COMPLETION_DIR)

# $(FISH_LOCAL_FILE):
# 	cp $(FISH_LOCAL_FILE_SAMPLE) $(FISH_LOCAL_FILE)

# $(FISH_FUNCTIONS_FILE):
# 	cp $(FISH_FUNCTIONS_FILE_SAMPLE) $(FISH_FUNCTIONS_FILE)

# $(FISH_DIR):
# 	mkdir -p $(FISH_DIR)
# 	ln -sf $(SELF_FISH_DIR)/config.fish $(FISH_DIR)/config.fish
# 	ln -sf $(SELF_FISH_DIR)/local.fish $(FISH_DIR)/local.fish
# 	ln -sf $(SELF_FISH_DIR)/functions.fish $(FISH_DIR)/functions.fish

# $(FISH_COMPLETION_DIR):
# 	mkdir -p $(FISH_COMPLETION_DIR)
# 	ln -sf $(SELF_FISH_DIR)/completions/aws.fish $(FISH_COMPLETION_DIR)/aws.fish
# 	ln -sf $(SELF_FISH_DIR)/completions/cdk.fish $(FISH_COMPLETION_DIR)/cdk.fish
# 	ln -sf $(SELF_FISH_DIR)/completions/ros.fish $(FISH_COMPLETION_DIR)/ros.fish
# 	ln -sf $(SELF_FISH_DIR)/completions/sbcl.fish $(FISH_COMPLETION_DIR)/sbcl.fish
# 	ln -sf $(SELF_FISH_DIR)/completions/pry.fish $(FISH_COMPLETION_DIR)/pry.fish
# 	ln -sf $(SELF_FISH_DIR)/completions/zat.fish $(FISH_COMPLETION_DIR)/zat.fish
# 	curl $(FISH_GHQ_COMPLETION_FILE) -o $(FISH_COMPLETION_DIR)/ghq.fish
# 	curl $(FISH_DOCKER_COMPLETION_FILE) -o $(FISH_COMPLETION_DIR)/docker.fish
# 	curl $(FISH_DOCKER_COMPOSE_COMPLETION_FILE) -o $(FISH_COMPLETION_DIR)/docker-compose.fish
