[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = "vim-denops/denops.vim"

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set fileencoding=utf-8 fileformat=unix
'''

[[plugins]]
repo = 'mattn/vim-sl'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=250
'''

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = "vim-skk/skkeleton"
hook_add = '''
source ~/.config/nvim/plugins/skkeleton.vim
'''

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
source ~/.config/nvim/plugins/undotree.vim
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'coc#util#install()'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'mtth/scratch.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.vim
'''
