[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css','scss','sass']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_conceal = 0
'''

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''
on_ft = ['json']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_mode='a'
autocmd FileType html,css,blade EmmetInstall
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
let g:go_term_mode = 'split'
'''

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
let g:goimports_simplify = 1
'''

[[plugins]]
repo = 'pantharshit00/vim-prisma'
on_ft = ['prisma']

[[plugins]]
repo = '0robustus1/vim-tmux-conf'
on_ft = ['tmuxconf']
hook_add = '''
au BufRead,BufNewFile dot.tmux.conf setf tmuxconf
'''

[[plugins]]
repo = 'sherylynn/vim-elisp'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'nvim-orgmode/orgmode'
depends = 'nvim-treesitter'
on_lua = 'orgmode'
hook_add = '''
source ~/.config/nvim/plugins/orgmode.vim
'''

[[plugins]]
repo = 'jwalton512/vim-blade'
hook_add = '''
let g:blade_custom_directives_pairs = {
      \   'markdown': 'endmarkdown',
      \   'cache': 'endcache',
      \ }
'''
