[[plugins]]
repo = 'dracula/vim'
hook_add = '''
colorscheme dracula
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_faster = 1
let g:indentLine_char = '¦'
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
set laststatus=2
set noshowmode
'''

[[plugins]]
repo = ''
